apiVersion: v1
kind: Secret
metadata:
  name: drone-server-secret
data:
  
  DRONE_RPC_SECRET: YOUR_SECRET # openssl rand -hex 16
  DRONE_GITHUB_CLIENT_ID: YOU_GITHUB_CLIENT_ID
  DRONE_GITHUB_CLIENT_SECRET: YOU_GITHUB_CLIENT_SECRET
